export const presets = [
    {
        name: "MyPreset",
        importString: "N4IghgNg5g9gTgSwC4AsC2IBcIDOB3AUwIAcAZBAOwJABoRLiBXJLAbVAA8sA2AFgHYAdPwCsdAJ5YAzFO7D+suggAmWegA4pABikBOHQEZe3fbRAQwAIwIQ1AQRABfGpywiDc0RKwAmdb0EtLX5uJVVsBAMRIN0pH10+HykRMwtrW2wAIScXEC5MfnUtYTEQSUwDf0FeXnVdMLVIoO5uHxEi9UKfVKsbNQBhHNdMAXUS7wqi6pbQ+nD6AW5NSv5REW4e9LUAESG8rF4PcbLfEQCjBoiDKUOtbm0-M-VNvuwAUT38kT9j8pvi0SzFSNAwGJJaXjrfwJZ50NKvEAAMScAF06MQ4DAoHACDgcFgtI4gA"
    }
]